# Generated by Django 5.2.7 on 2025-10-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='PhoneNumber',
            field=models.IntegerField(),
        ),
    ]
