# Generated by Django 5.2.7 on 2025-10-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_registeruser_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeruser',
            name='confirm_password',
        ),
        migrations.AddField(
            model_name='registeruser',
            name='Address',
            field=models.TextField(default='Varansi, India'),
        ),
    ]
